#!/usr/bin/env python3

import ctypes
import os

from UDP import UDP

libcustomwrapper_filename = "libcustomparser.so"

# Since our shared library function will return a struct, we need to define
# it in python too.
class udp_msg_t(ctypes.Structure):
    ubyte_512 = ctypes.c_ubyte * 512
    _fields_ = [('src_port', ctypes.c_ushort),
                ('dest_port', ctypes.c_ushort),
                ('length', ctypes.c_ushort),
                ('checksum', ctypes.c_ushort),
                ('data', ubyte_512)]

def main():
    # Import our warpper library
    libcustomwrapper_path = (libcustomwrapper_filename)
    libcustomwrapper = ctypes.CDLL(libcustomwrapper_path)
    libcustomwrapper.custom_parse.restype = ctypes.c_void_p

    # Generate a UDP message
    udp_msg = UDP(25515, 32316, "This is a data payload")

    # Parse our UDP message
    void_p_ret = libcustomwrapper.custom_parse(udp_msg.serialized, len(udp_msg.serialized))
    # Cast the retured void* into a udp_msg_t python object
    udp_msg_t_ret = udp_msg_t.from_address(void_p_ret)

    # Print out the data received from our custom parse function
    print("Parsed Data:")
    print(f"  Source Port: {udp_msg_t_ret.src_port}")
    print(f"  Destination Port: {udp_msg_t_ret.dest_port}")
    print(f"  Payload Length: {udp_msg_t_ret.length}")
    print(f"  Checksum: {udp_msg_t_ret.checksum}")
    print(f"  Data: ", end='')
    for i in range(udp_msg_t_ret.length):
        print(f"{chr(udp_msg_t_ret.data[i])}", end='')
    print()

    # Free the memory of the udp_msg_t that was generated by the parse function
    libcustomwrapper.free_udp_msg(void_p_ret)
    # Delete the instance in python also
    del udp_msg_t_ret

if __name__ == '__main__':
    main()
